services:
  postgres:
    container_name: postgres-sql-social-books
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: book_social_network
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - social-books
    restart: unless-stopped

  mail-dev:
    container_name: mail-dev-socialbooks
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025

networks:
  social-books:
    driver: bridge

volumes:
  postgres:
    driver: local
